#!/usr/bin/env bun
// `src/ui/tokens.css` is the single --bk-* token block, but `theme.ts` serves its stylesheet as a
// string and cannot import CSS. This lifts the two declaration lists out of the CSS into a module
// tsc can resolve, so the tokens live in exactly one file without a second copy in TypeScript.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export interface TokenDeclaration {
  name: string;
  value: string;
}

// Markers rather than a CSS parser: the blocks are flat declaration lists by construction, and a
// stray rule between markers is the only way this could mislead — which the `--bk-` filter catches.
function block(css: string, variant: 'light' | 'dark'): string {
  const start = `/* reserva:tokens-${variant} */`;
  const end = `/* /reserva:tokens-${variant} */`;
  const from = css.indexOf(start);
  const to = css.indexOf(end);
  if (from === -1 || to === -1) throw new Error(`tokens.css is missing the ${start} … ${end} markers`);
  return css.slice(from + start.length, to);
}

export function tokenDeclarations(css: string, variant: 'light' | 'dark'): TokenDeclaration[] {
  return [...block(css, variant).matchAll(/(--bk-[\w-]+)\s*:\s*([^;]+);/g)]
    .map((match) => ({ name: match[1] as string, value: (match[2] as string).trim() }));
}

export function readTokensCss(repoRoot: string): string {
  return readFileSync(resolve(repoRoot, 'src/ui/tokens.css'), 'utf8');
}

function serialize(declarations: TokenDeclaration[]): string {
  return declarations.map(({ name, value }) => `\n  ${name}: ${value};`).join('');
}

export function renderUiTokensModule(css: string): string {
  return [
    '// GENERATED by scripts/generate-ui-tokens.ts from src/ui/tokens.css. Do not edit.',
    'export const lightTokens = `'
      + serialize(tokenDeclarations(css, 'light')) + '`;',
    'export const darkTokens = `'
      + serialize(tokenDeclarations(css, 'dark')) + '`;',
    '',
  ].join('\n');
}

export function generateUiTokens(repoRoot: string): string {
  const css = readTokensCss(repoRoot);
  const target = resolve(repoRoot, 'src/ui/generated/tokens.ts');
  const source = renderUiTokensModule(css);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, source);
  return 'src/ui/generated/tokens.ts written from src/ui/tokens.css';
}

if (import.meta.main) {
  console.log(generateUiTokens(resolve(dirname(fileURLToPath(import.meta.url)), '..')));
}
