#!/usr/bin/env bun
// `src/ui/tokens.css` is the single --bk-* token block, but neither delivery channel can load it
// as-is: `theme.ts` serves its stylesheet as a string and cannot import CSS, and the embeddable
// components must theme `.bk-embed` rather than the host's :root. This lifts the two declaration
// lists out of the CSS into one output per channel, so the values live in exactly one file.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export interface TokenDeclaration {
  name: string;
  value: string;
}

// Markers rather than a CSS parser: the blocks are flat declaration lists by construction, and a
// stray rule between markers is the only way this could mislead — which the `--bk-` filter catches.
function block(css: string, variant: 'light' | 'dark'): string {
  const start = `/* reserva:tokens-${variant} */`;
  const end = `/* /reserva:tokens-${variant} */`;
  const from = css.indexOf(start);
  const to = css.indexOf(end);
  if (from === -1 || to === -1) throw new Error(`tokens.css is missing the ${start} … ${end} markers`);
  return css.slice(from + start.length, to);
}

export function tokenDeclarations(css: string, variant: 'light' | 'dark'): TokenDeclaration[] {
  return [...block(css, variant).matchAll(/(--bk-[\w-]+)\s*:\s*([^;]+);/g)]
    .map((match) => ({ name: match[1] as string, value: (match[2] as string).trim() }));
}

export function readTokensCss(repoRoot: string): string {
  return readFileSync(resolve(repoRoot, 'src/ui/tokens.css'), 'utf8');
}

function serialize(declarations: TokenDeclaration[], indent = '  '): string {
  return declarations.map(({ name, value }) => `\n${indent}${name}: ${value};`).join('');
}

function record(declarations: TokenDeclaration[]): string {
  return `{${declarations.map(({ name, value }) => `\n  ${JSON.stringify(name)}: ${JSON.stringify(value)},`).join('')}\n}`;
}

export function renderUiTokensModule(css: string): string {
  const light = tokenDeclarations(css, 'light');
  const dark = tokenDeclarations(css, 'dark');
  return [
    '// GENERATED by scripts/generate-ui-tokens.ts from src/ui/tokens.css. Do not edit.',
    `export const lightTokens = \`${serialize(light)}\`;`,
    `export const darkTokens = \`${serialize(dark)}\`;`,
    `export const lightTokenValues: Readonly<Record<string, string>> = ${record(light)};`,
    `export const darkTokenValues: Readonly<Record<string, string>> = ${record(dark)};`,
    '',
  ].join('\n');
}

// Every selector sits inside :where() so a host's own `.bk-embed { --bk-accent: … }` wins in both
// schemes. A host `data-theme` on any ancestor forces the palette the way the pages' <html
// data-theme> does; forced dark comes after the OS rule because, at equal (zero) specificity,
// source order is what lets it win. Dark is screen-only so a printout is always the light palette.
export function renderEmbedTokensCss(css: string): string {
  const light = tokenDeclarations(css, 'light');
  const dark = tokenDeclarations(css, 'dark');
  return [
    '/* GENERATED by scripts/generate-ui-tokens.ts from src/ui/tokens.css. Do not edit. */',
    '',
    ':where(.bk-embed) {',
    `  color-scheme: light dark;${serialize(light)}`,
    '}',
    '@media screen and (prefers-color-scheme: dark) {',
    `  :where(.bk-embed:not([data-theme="light"] *)) {${serialize(dark, '    ')}`,
    '  }',
    '}',
    '@media screen {',
    '  :where([data-theme="dark"] .bk-embed) {',
    `    color-scheme: dark;${serialize(dark, '    ')}`,
    '  }',
    '}',
    ':where([data-theme="light"] .bk-embed) { color-scheme: light; }',
    '@media print {',
    '  :where(.bk-embed) { color-scheme: light; }',
    '}',
    '',
  ].join('\n');
}

export const UI_TOKEN_OUTPUTS = [
  { file: 'src/ui/generated/tokens.ts', render: renderUiTokensModule },
  { file: 'src/ui/generated/embed-tokens.css', render: renderEmbedTokensCss },
] as const;

export function generateUiTokens(repoRoot: string): string {
  const css = readTokensCss(repoRoot);
  for (const { file, render } of UI_TOKEN_OUTPUTS) {
    const target = resolve(repoRoot, file);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, render(css));
  }
  return `${UI_TOKEN_OUTPUTS.map(({ file }) => file).join(' and ')} written from src/ui/tokens.css`;
}

if (import.meta.main) {
  console.log(generateUiTokens(resolve(dirname(fileURLToPath(import.meta.url)), '..')));
}
