// Plan 018 (design decision 9): proves the widget's `pickupOptions` prop and the deprecated
// `pickupTypes` alias against the real Astro render pipeline (see
// tests/component/booking-widget-meeting-points.test.ts for why AstroContainer, not source-text
// assertions, is needed here).
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { experimental_AstroContainer as AstroContainer } from 'astro/container';
import { describe, expect, it } from 'vitest';
// @ts-expect-error -- resolved by vitest.component.config.ts's Astro Vite pipeline, not by tsc.
import BookingWidget from '../../src/components/BookingWidget.astro';

const baseProps = { tourSlug: 'oldTown', availabilityFrom: '2026-01-01', availabilityTo: '2026-01-02', locale: 'en' };
const fixturesDir = resolve(import.meta.dirname, '__fixtures__');

// dateLabelId is a fresh crypto.randomUUID() every render (Plan 014 item A), and AstroContainer's
// dev-mode component script tag embeds this machine's absolute repo path — both vary per
// environment/run and have nothing to do with the pickupOptions markup this test cares about, so
// both are normalized out before any byte-identity comparison.
function normalize(html: string): string {
  return html
    .replace(/bkw-date-label-[0-9a-f-]+/g, 'bkw-date-label-<id>')
    .replace(/src="[^"]*\/src\/components\/BookingWidget\.astro\?astro&type=script&index=0&lang\.ts"/g, 'src="<script-src>"');
}

async function render(props: Record<string, unknown>): Promise<string> {
  const container = await AstroContainer.create();
  return normalize(await container.renderToString(BookingWidget, { props }));
}

function readFixture(name: string): string {
  return readFileSync(resolve(fixturesDir, name), 'utf8');
}

// The CRITICAL byte-identity constraint (plan 018 done criterion): a config with no pickupOptions
// must produce markup identical, byte for byte, to what BookingWidget.astro rendered before this
// prop existed. These fixtures were captured from the pre-lane-D widget (see the plan's lane D
// instructions) and are never regenerated by this test — regenerating them here would make the
// comparison trivially pass against whatever the widget currently does, defeating the point.
describe('BookingWidget.astro byte-identity (plan 018 design decision 9)', () => {
  it('no pickupOptions (and no pickupTypes) renders exactly like the pre-018 widget', async () => {
    expect(await render(baseProps)).toBe(readFixture('widget-default-render.html'));
  });

  it('explicit pickupTypes=[default,custom] alias renders exactly like the pre-018 widget', async () => {
    expect(await render({ ...baseProps, pickupTypes: ['default', 'custom'] })).toBe(readFixture('widget-pickuptypes-alias-render.html'));
  });

  it('two meetingPoints with no pickupOptions renders exactly like the pre-018 widget', async () => {
    const html = await render({
      ...baseProps,
      meetingPoints: [
        { id: 'fountain', label: 'Main square fountain' },
        { id: 'station', label: 'Riverside dock' },
      ],
    });
    expect(html).toBe(readFixture('widget-two-meeting-points-render.html'));
  });

  it('the pickupTypes alias never emits data-uses-meeting-point', async () => {
    const html = await render(baseProps);
    expect(html).not.toContain('data-uses-meeting-point');
  });
});

const mazePickupOptions = [
  { id: 'meeting_point', label: 'Meeting point', usesMeetingPoint: true },
  { id: 'custom_dropoff', label: 'Custom drop-off', usesMeetingPoint: true },
  { id: 'custom_pickup', label: 'Custom pick-up', usesMeetingPoint: false },
  { id: 'custom_both', label: 'Custom pick-up & drop-off', usesMeetingPoint: false },
];

const mazePricing = [
  { maxPeople: 4, pickup: 'meeting_point', priceCents: 18000 },
  { maxPeople: 4, pickup: 'custom_dropoff', priceCents: 20000 },
  { maxPeople: 4, pickup: 'custom_pickup', priceCents: 20000 },
  { maxPeople: 4, pickup: 'custom_both', priceCents: 21000 },
];

describe('BookingWidget.astro pickupOptions prop (plan 018 design decision 9)', () => {
  it('renders four declared options with their declared labels and data-uses-meeting-point attributes', async () => {
    const html = await render({ ...baseProps, pickupOptions: mazePickupOptions });
    const radios = [...html.matchAll(/<input type="radio" name="pickupType" value="([^"]+)"[^>]*>/g)];
    expect(radios.map((m) => m[1])).toEqual(['meeting_point', 'custom_dropoff', 'custom_pickup', 'custom_both']);
    expect(radios[0]?.[0]).toContain('data-uses-meeting-point="true"');
    expect(radios[1]?.[0]).toContain('data-uses-meeting-point="true"');
    expect(radios[2]?.[0]).toContain('data-uses-meeting-point="false"');
    expect(radios[3]?.[0]).toContain('data-uses-meeting-point="false"');
    expect(html).toContain('Meeting point');
    expect(html).toContain('Custom drop-off');
    expect(html).toContain('Custom pick-up</span>');
    expect(html).toContain('Custom pick-up &amp; drop-off');
  });

  it('falls back to the catalog label/hint for a declared default/custom id with no label of its own', async () => {
    const html = await render({
      ...baseProps,
      pickupOptions: [
        { id: 'default', usesMeetingPoint: true },
        { id: 'custom', usesMeetingPoint: false },
      ],
    });
    expect(html).toContain('Meeting point');
    expect(html).toContain('Meet us at the tour start point');
    expect(html).toContain('Custom pickup');
    expect(html).toContain('We pick you up at your address');
  });

  it('falls back to the raw id for a declared option with no label and an id outside default/custom, and omits the hint span', async () => {
    const html = await render({
      ...baseProps,
      pickupOptions: [
        { id: 'harbor_pickup', usesMeetingPoint: true },
        { id: 'custom', usesMeetingPoint: false },
      ],
    });
    expect(html).toContain('<span class="bkw-pickup-label">harbor_pickup</span>');
    // No hint span for harbor_pickup: its <label> block must not contain bkw-pickup-hint before
    // the next pickup's <label> starts.
    const harborBlock = html.slice(html.indexOf('harbor_pickup'), html.indexOf('value="custom"'));
    expect(harborBlock).not.toContain('bkw-pickup-hint');
  });

  // The hidden input must carry the flag too: syncMeetingPoints falls back to the legacy
  // id === 'custom' heuristic when the attribute is absent, which would wrongly show/require the
  // meeting-point group for a sole non-custom option with usesMeetingPoint: false (and hide it for
  // a sole custom option with usesMeetingPoint: true).
  it('a single declared option renders a hidden input, not a radio group, carrying its data-uses-meeting-point flag', async () => {
    const trueHtml = await render({ ...baseProps, pickupOptions: [{ id: 'meeting_point', label: 'Meeting point', usesMeetingPoint: true }] });
    expect(trueHtml).toContain('<input type="hidden" name="pickupType" value="meeting_point" data-uses-meeting-point="true">');
    expect(trueHtml).not.toContain('<fieldset class="bkw-field">\n      <legend class="bkw-label">Where do we meet?');

    const falseHtml = await render({ ...baseProps, pickupOptions: [{ id: 'hotel_pickup', label: 'Hotel pickup', usesMeetingPoint: false }] });
    expect(falseHtml).toContain('<input type="hidden" name="pickupType" value="hotel_pickup" data-uses-meeting-point="false">');
  });

  it('resolves the four-option non-additive price table (180/200/200/210) keyed by the declared ids, not a fixed pair', async () => {
    const html = await render({ ...baseProps, pickupOptions: mazePickupOptions, pricing: mazePricing });
    const island = html.match(/<script type="application\/json" data-bookkit-data>([^<]+)<\/script>/);
    expect(island).toBeTruthy();
    const data = JSON.parse(island![1]!);
    // Each id's single maxPeople:4 row covers every party size 1-4 at one flat price (index 0 is
    // never set — the table is 1-indexed by people count — so JSON round-trips it as null).
    expect(data.resolvedPrices).toEqual({
      meeting_point: [null, 18000, 18000, 18000, 18000],
      custom_dropoff: [null, 20000, 20000, 20000, 20000],
      custom_pickup: [null, 20000, 20000, 20000, 20000],
      custom_both: [null, 21000, 21000, 21000, 21000],
    });
  });

  it('meeting-point toggle: usesMeetingPoint:false hides the group, usesMeetingPoint:true shows it (via data-uses-meeting-point, not a hardcoded id)', async () => {
    const html = await render({
      ...baseProps,
      pickupOptions: mazePickupOptions,
      meetingPoints: [
        { id: 'a', label: 'Point A' },
        { id: 'b', label: 'Point B' },
      ],
    });
    // custom_pickup and custom_both both carry usesMeetingPoint:false despite neither being named
    // 'custom' — proves the toggle is driven by the data attribute, not an id === 'custom' check.
    expect(html).toContain('data-uses-meeting-point="false"');
    const radios = [...html.matchAll(/<input type="radio" name="pickupType" value="([^"]+)"[^>]*data-uses-meeting-point="([^"]+)"/g)];
    expect(radios.find((m) => m[1] === 'custom_pickup')?.[2]).toBe('false');
    expect(radios.find((m) => m[1] === 'meeting_point')?.[2]).toBe('true');
  });
});
